"""
title: ArXiv Paper to Markdown Converter
author: Generated by Grok (xAI)
version: 1.0
license: MIT
description: Search arXiv for papers and convert them to clean Markdown (LaTeX source via pandoc with full $ / $$ equation preservation, or PDF fallback via PyMuPDF). Handles single-file and multi-file LaTeX (via extraction + pandoc with relative \input{} resolution). Returns ready-to-use Markdown for LLMs.
version: 0.3.6
"""

import arxiv
import requests
import tarfile
import tempfile
import os
import subprocess
from pathlib import Path
import fitz  # PyMuPDF
from typing import List, Optional, Dict
import unittest
from unittest.mock import patch


class Tools:
    def __init__(self):
        """Initialize the ArXiv tool. Citation enabled for visibility in Open-WebUI."""
        self.citation = True

    def search_arxiv(self, query: str, max_results: int = 10) -> str:
        """
        Search arXiv for papers matching the query.

        :param query: Search query (e.g., "transformer attention mechanism" or author:arxiv_id)
        :param max_results: Maximum number of results to return (default 10, max 50)
        :return: Formatted string of matching papers with ID, title, authors, abstract snippet, and PDF link.
        """
        try:
            search = arxiv.Search(
                query=query,
                max_results=max_results,
                sort_by=arxiv.SortCriterion.Relevance,
            )
            results: List[arxiv.Result] = list(search.results())
            
            if not results:
                return "No papers found for the query."
            
            output = f"**Found {len(results)} papers for query: '{query}'**\n\n"
            for i, result in enumerate(results, 1):
                authors = ", ".join([author.name for author in result.authors])
                abstract_snippet = result.summary[:300] + "..." if len(result.summary) > 300 else result.summary
                arxiv_id = result.get_short_id()  # e.g., 1706.03762
                output += f"{i}. **{result.title}**\n"
                output += f"   ID: `{arxiv_id}`\n"
                output += f"   Authors: {authors}\n"
                output += f"   Published: {result.published.strftime('%Y-%m-%d')}\n"
                output += f"   Abstract: {abstract_snippet}\n"
                output += f"   PDF: {result.pdf_url}\n"
                output += f"   Source: https://arxiv.org/src/{arxiv_id}\n\n"
            
            return output.strip()
        
        except Exception as e:
            return f"Error searching arXiv: {str(e)}"

    def get_paper_markdown(self, arxiv_id: str) -> str:
        """
        Convert an arXiv paper to Markdown. Prioritizes LaTeX source (single or multi-file with \input{}).
        Falls back to PDF parsing for pre-LaTeX/old papers without source.

        :param arxiv_id: arXiv ID (e.g., "1706.03762" or "2305.12345")
        :return: Full Markdown of the paper (title, authors, abstract + body). Equations preserved as $...$ (inline) and $$...$$ (display).
        """
        # Step 1: Fetch metadata (always available)
        try:
            search = arxiv.Search(id_list=[arxiv_id])
            result = next(search.results())
            title = result.title
            authors = ", ".join([a.name for a in result.authors])
            abstract = result.summary
            published = result.published.strftime("%Y-%m-%d")
        except StopIteration:
            return f"❌ Paper not found: {arxiv_id}. Please check the ID and try again."
        except Exception as e:
            return f"❌ Error fetching metadata for {arxiv_id}: {str(e)}"

        header = f"# {title}\n\n"
        header += f"**Authors:** {authors}  \n"
        header += f"**Published:** {published}  \n"
        header += f"**arXiv ID:** `{arxiv_id}`  \n\n"
        header += f"## Abstract\n\n{abstract}\n\n"
        header += "## Full Content\n\n"

        # Step 2: Try LaTeX source (handles single .tex or multi-file with \input{})
        with tempfile.TemporaryDirectory() as tmp_dir:
            source_url = f"https://arxiv.org/src/{arxiv_id}"
            try:
                resp = requests.get(source_url, stream=True, timeout=30)
                if resp.status_code == 200:
                    content_type = resp.headers.get("content-type", "").lower()
                    extracted = False
                    
                    # Handle tar.gz (most common for multi-file)
                    if "tar" in content_type or "gzip" in content_type or source_url.endswith((".tar.gz", ".tgz")):
                        try:
                            with tarfile.open(fileobj=resp.raw, mode="r:gz") as tar:
                                tar.extractall(path=tmp_dir)
                            extracted = True
                        except tarfile.TarError:
                            pass
                    
                    # Fallback for rare single .tex.gz or plain .tex
                    elif "text" in content_type or source_url.endswith(".tex"):
                        tex_path = os.path.join(tmp_dir, f"{arxiv_id}.tex")
                        with open(tex_path, "wb") as f:
                            f.write(resp.content)
                        extracted = True
                    
                    if extracted:
                        # Find main .tex (looks for \documentclass first, then any .tex)
                        main_tex = self._find_main_tex(tmp_dir)
                        if main_tex:
                            try:
                                # pandoc compiles the full document (resolves \input{} relative to cwd)
                                proc = subprocess.run(
                                    [
                                        "pandoc",
                                        "-f", "latex",
                                        "-t", "markdown",
                                        "--standalone",
                                        "--wrap=none",
                                        main_tex,
                                    ],
                                    cwd=tmp_dir,
                                    capture_output=True,
                                    text=True,
                                    timeout=60,
                                    check=False,
                                )
                                if proc.returncode == 0:
                                    body = proc.stdout
                                    # pandoc guarantees proper $...$ (inline) and $$...$$ (display) syntax
                                    return header + body
                                else:
                                    body = f"⚠️ Pandoc conversion warning (return code {proc.returncode}):\n{proc.stderr}"
                            except FileNotFoundError:
                                body = "⚠️ pandoc not found on system. Install pandoc to enable LaTeX → Markdown."
                            except subprocess.TimeoutExpired:
                                body = "⚠️ LaTeX conversion timed out (paper too large/complex)."
                            except Exception as e:
                                body = f"⚠️ LaTeX conversion error: {str(e)}"
                        else:
                            body = "⚠️ No .tex file found in source archive."
                    else:
                        body = "⚠️ Could not parse source archive."
                else:
                    body = "⚠️ No LaTeX source available (pre-2000 or source-restricted paper)."
            except requests.RequestException:
                body = "⚠️ Failed to download LaTeX source."

            # Step 3: PDF fallback (PyMuPDF text extraction)
            if "No LaTeX" in body or "⚠️" in body or "failed" in body.lower():
                pdf_url = f"https://arxiv.org/pdf/{arxiv_id}.pdf"
                try:
                    pdf_resp = requests.get(pdf_url, stream=True, timeout=30)
                    if pdf_resp.status_code == 200:
                        pdf_path = os.path.join(tmp_dir, "paper.pdf")
                        with open(pdf_path, "wb") as f:
                            for chunk in pdf_resp.iter_content(chunk_size=8192):
                                f.write(chunk)
                        
                        doc = fitz.open(pdf_path)
                        body = ""
                        for i, page in enumerate(doc):
                            text = page.get_text("text")
                            body += f"### Page {i+1}\n\n{text.strip()}\n\n"
                        doc.close()
                        body = f"**Note:** This paper had no LaTeX source. Text extracted from PDF (equations may appear as plain text).\n\n{body}"
                    else:
                        body = "❌ Could not download PDF."
                except Exception as e:
                    body = f"❌ PDF fallback failed: {str(e)}"

            return header + body

    def _find_main_tex(self, directory: str) -> Optional[str]:
        """Helper: Find the primary .tex file (contains \documentclass) or fallback to first .tex."""
        tex_files = list(Path(directory).rglob("*.tex"))
        if not tex_files:
            return None
        
        for tex_path in tex_files:
            try:
                with open(tex_path, "r", encoding="utf-8", errors="ignore") as f:
                    head = f.read(2000)
                    if "\\documentclass" in head:
                        return str(tex_path)
            except Exception:
                continue
        
        # Fallback
        return str(tex_files[0])


# ====================== UNIT TESTS ======================
class TestArxivTool(unittest.TestCase):
    def setUp(self):
        self.tool = Tools()

    def test_paper_searching(self):
        """Test paper searching returns valid formatted results."""
        results = self.tool.search_arxiv("attention is all you need", max_results=3)
        self.assertIsInstance(results, str)
        self.assertIn("Attention Is All You Need", results)
        self.assertIn("1706.03762", results)
        self.assertGreater(len(results), 200)

    def test_equation_conversion_inline_and_block(self):
        """Test pandoc retains proper $...$ and $$...$$ syntax (independent of full paper)."""
        sample_latex = r"""
\documentclass{article}
\begin{document}
Inline equation: $E = mc^2$.

Block equation:
\[
\int_0^\infty e^{-x^2} \, dx = \frac{\sqrt{\pi}}{2}
\]
\end{document}
"""
        with tempfile.TemporaryDirectory() as tmp:
            tex_path = os.path.join(tmp, "test.tex")
            with open(tex_path, "w", encoding="utf-8") as f:
                f.write(sample_latex)
            
            try:
                proc = subprocess.run(
                    ["pandoc", "-f", "latex", "-t", "markdown", "--standalone", tex_path],
                    cwd=tmp,
                    capture_output=True,
                    text=True,
                    timeout=10,
                )
                self.assertEqual(proc.returncode, 0)
                md = proc.stdout
                self.assertIn("$E = mc^2$", md)          # inline preserved
                self.assertIn("$$", md)                   # display uses $$
                self.assertIn(r"\int_0^\infty e^{-x^2}", md)
            except FileNotFoundError:
                self.skipTest("pandoc not available in test environment")
            except Exception as e:
                self.fail(f"Equation conversion test failed: {e}")

    def test_full_markdown_conversion_actual_latex_paper(self):
        """Test full conversion on a real modern LaTeX paper (multi-file capable)."""
        md = self.tool.get_paper_markdown("1706.03762")  # Attention Is All You Need
        self.assertIsInstance(md, str)
        self.assertGreater(len(md), 5000)
        self.assertIn("# Attention Is All You Need", md)
        self.assertIn("## Abstract", md)
        # Check equation preservation (paper has many)
        self.assertTrue("$" in md or "$$" in md)
        self.assertIn("Transformer", md)

    def test_pre_latex_pdf_paper(self):
        """Test PDF fallback on an older paper (many pre-~2000 have limited/no source)."""
        # 1993 cond-mat paper (source often unavailable or minimal)
        md = self.tool.get_paper_markdown("cond-mat/9301011")
        self.assertIsInstance(md, str)
        self.assertGreater(len(md), 1000)
        self.assertIn("# ", md)  # title present
        self.assertIn("## Abstract", md)
        # PDF fallback indicator
        self.assertTrue("Page 1" in md or "extracted from PDF" in md.lower())

    def test_non_existent_paper(self):
        """Test graceful handling of invalid/non-existent arXiv ID."""
        md = self.tool.get_paper_markdown("9999.99999")
        self.assertIsInstance(md, str)
        self.assertIn("Paper not found", md)
        self.assertIn("9999.99999", md)


if __name__ == "__main__":
    # Run tests when executed directly (for development/verification)
    unittest.main(verbosity=2)