"""
title: ComfyUI ACE Step Audio Generator
description: Tool to generate songs using the ACE Step workflow via the ComfyUI API. Accepts tags and lyrics (generated by the LLM), and allows full control over the workflow JSON and node numbers. Returns an embedded audio player and download link.
author: Haervwe
author_url: https://github.com/Haervwe/open-webui-tools/
funding_url: https://github.com/Haervwe/open-webui-tools
version: 1.1.2
required_open_webui_version: 0.8.11
"""

import json
import random
from typing import Optional, Dict, Any, Callable, Awaitable, cast, Union, Tuple
import aiohttp
import asyncio
import uuid
import os
from pydantic import BaseModel, Field

from fastapi import Request, UploadFile
from fastapi.responses import HTMLResponse
from open_webui.models.users import Users
from open_webui.routers.files import upload_file_handler
import io
import re


async def wait_for_completion_ws(
    comfyui_ws_url: str,
    comfyui_http_url: str,
    prompt_id: str,
    client_id: str,
    max_wait_time: int,
    event_emitter: Optional[Callable[[Any], Awaitable[None]]] = None,
    headers: Optional[Dict[str, str]] = None,
) -> Dict[str, Any]:
    """
    Waits for ComfyUI job completion using WebSocket for real-time updates.
    Returns the job output data upon successful execution.
    """
    start_time = asyncio.get_event_loop().time()
    job_data_output = None

    try:
        async with aiohttp.ClientSession(headers=headers).ws_connect(
            f"{comfyui_ws_url}?clientId={client_id}"
        ) as ws:
            # Suppress noisy status emissions: UI now logs each message; keep silent during progress

            async for msg in ws:
                if asyncio.get_event_loop().time() - start_time > max_wait_time:
                    raise TimeoutError(
                        f"WebSocket wait timed out after {max_wait_time}s"
                    )

                if msg.type == aiohttp.WSMsgType.TEXT:
                    try:
                        message = json.loads(msg.data)
                        if "type" not in message:
                            continue
                        msg_type = message["type"]
                        data = message.get("data", {})

                        if msg_type == "status":
                            # Ignore queue status updates to reduce UI clutter
                            pass

                        elif (
                            msg_type == "execution_start"
                            and data.get("prompt_id") == prompt_id
                        ):
                            # Suppress execution start notification
                            pass

                        elif (
                            msg_type == "executing"
                            and data.get("prompt_id") == prompt_id
                        ):
                            # Suppress per-node executing updates
                            pass

                        elif (
                            msg_type == "progress"
                            and data.get("prompt_id") == prompt_id
                        ):
                            # Suppress progress updates
                            pass

                        elif (
                            msg_type == "execution_cached"
                            and data.get("prompt_id") == prompt_id
                        ):
                            # Suppress cached notice
                            pass

                            async with aiohttp.ClientSession(headers=headers) as http_session:
                                async with http_session.get(
                                    f"{comfyui_http_url}/history/{prompt_id}"
                                ) as resp:
                                    if resp.status == 200:
                                        history = await resp.json()
                                        if prompt_id in history:
                                            return history[prompt_id]
                            raise Exception(
                                "Job was cached, but failed to retrieve output from history."
                            )

                        elif (
                            msg_type == "executed"
                            and data.get("prompt_id") == prompt_id
                        ):
                            # Defer success messaging to caller
                            job_data_output = data.get("output", {})
                            async with aiohttp.ClientSession(headers=headers) as http_session:
                                async with http_session.get(
                                    f"{comfyui_http_url}/history/{prompt_id}"
                                ) as resp:
                                    if resp.status == 200:
                                        history = await resp.json()
                                        if prompt_id in history:
                                            return history[prompt_id]

                            if job_data_output:
                                return {"outputs": job_data_output}  # type: ignore[return-value]
                            raise Exception(
                                "Job executed, but failed to retrieve output from WebSocket or history."
                            )

                        elif (
                            msg_type == "execution_error"
                            and data.get("prompt_id") == prompt_id
                        ):
                            error_details = data.get(
                                "exception_message", "Unknown error"
                            )
                            node_id = data.get("node_id", "N/A")
                            node_type = data.get("node_type", "N/A")
                            error_str = f"ComfyUI job failed on node {node_id} ({node_type}). Error: {error_details}"
                            # Defer failure messaging to caller
                            raise Exception(error_str)

                    except json.JSONDecodeError:
                        # Silence non-JSON WS messages
                        pass
                    except Exception as e:
                        if "ComfyUI job" in str(e) or isinstance(e, TimeoutError):
                            raise
                        # Suppress intermediate WS processing errors
                        pass

                elif msg.type == aiohttp.WSMsgType.ERROR:
                    raise Exception(f"WebSocket connection error: {ws.exception()}")
                elif msg.type == aiohttp.WSMsgType.CLOSED:
                    if not job_data_output:
                        raise Exception(
                            "WebSocket closed unexpectedly before completion."
                        )
                    break

            if not job_data_output:
                raise TimeoutError(
                    "WebSocket connection closed or timed out without explicit completion event."
                )

            return {"outputs": job_data_output}

    except asyncio.TimeoutError:
        raise TimeoutError(f"Overall wait/connection timed out after {max_wait_time}s")
    except Exception as e:
        raise Exception(f"Error during WebSocket communication: {e}")


def extract_audio_files(job_data: Dict[str, Any]) -> list[Dict[str, str]]:
    """Extract audio file paths from completed job data."""
    audio_files: list[Dict[str, str]] = []
    node_outputs_dict = cast(Dict[str, Any], job_data.get("outputs", {}))
    for _node_id, node_output_content in node_outputs_dict.items():
        if isinstance(node_output_content, dict):
            node_output_dict: Dict[str, Any] = cast(Dict[str, Any], node_output_content)
            for key_holding_files in [
                "audio",
                "files",
                "filenames",
                "output",
                "outputs",
            ]:
                if key_holding_files in node_output_dict:
                    potential_files_raw: Any = node_output_dict.get(key_holding_files)
                    if isinstance(potential_files_raw, list):
                        potential_files_list: list[Union[Dict[str, Any], str]] = cast(
                            list[Union[Dict[str, Any], str]], potential_files_raw
                        )
                        for file_info_item in potential_files_list:
                            filename = None
                            subfolder = ""
                            if isinstance(file_info_item, dict):
                                file_info_dict: Dict[str, Any] = file_info_item
                                fn_val: Any = file_info_dict.get("filename")
                                filename = fn_val if isinstance(fn_val, str) else None
                                subfolder_val: Any = file_info_dict.get("subfolder", "")
                                subfolder = (
                                    str(subfolder_val)
                                    if subfolder_val is not None
                                    else ""
                                )
                            else:
                                # Treat any non-dict entry as a filename string
                                filename = str(file_info_item)

                            if filename is not None and filename.lower().endswith(
                                (".wav", ".mp3", ".flac", ".ogg")
                            ):
                                audio_files.append(
                                    {
                                        "filename": filename,
                                        "subfolder": subfolder.strip("/"),
                                    }
                                )
    return audio_files


async def download_audio_to_storage(
    request: Request,
    user,
    comfyui_http_url: str,
    filename: str,
    subfolder: str = "",
    song_name: str = "",
    headers: Optional[Dict[str, str]] = None,
) -> Optional[str]:
    try:
        file_extension = os.path.splitext(filename)[1] or ".mp3"
        if song_name:
            safe_name = re.sub(r"[^\w\s-]", "", song_name).strip().replace(" ", "_")
            local_filename = f"{safe_name}{file_extension}"
        else:
            local_filename = f"ace_step_{uuid.uuid4().hex[:8]}{file_extension}"

        mime_map = {
            ".mp3": "audio/mpeg",
            ".wav": "audio/wav",
            ".flac": "audio/flac",
            ".ogg": "audio/ogg",
        }
        content_type = mime_map.get(file_extension.lower(), "audio/mpeg")

        subfolder_param = f"&subfolder={subfolder}" if subfolder else ""
        comfyui_file_url = (
            f"{comfyui_http_url}/view?filename={filename}&type=output{subfolder_param}"
        )

        async with aiohttp.ClientSession(headers=headers) as session:
            async with session.get(comfyui_file_url) as response:
                if response.status == 200:
                    audio_content = await response.read()

                    upload_file = UploadFile(
                        file=io.BytesIO(audio_content),
                        filename=local_filename,
                        headers={"content-type": content_type},
                    )

                    file_item = upload_file_handler(
                        request,
                        file=upload_file,
                        metadata={},
                        process=False,
                        user=user,
                    )

                    if file_item and getattr(file_item, "id", None):
                        file_id = str(getattr(file_item, "id", ""))
                        relative_path = request.app.url_path_for(
                            "get_file_content_by_id", id=file_id
                        )
                        return f"{relative_path}"

                    print("[DEBUG] upload_file_handler returned no file item")
                    return None
                else:
                    print(
                        f"[DEBUG] Failed to download audio from ComfyUI: HTTP {response.status}"
                    )
                    return None

    except Exception as e:
        print(f"[DEBUG] Error uploading audio to storage: {str(e)}")
        return None


async def get_loaded_models_async(
    api_url: str = "http://localhost:11434",
) -> list[Dict[str, Any]]:
    """Get all currently loaded models in VRAM"""
    try:
        async with aiohttp.ClientSession() as session:
            async with session.get(f"{api_url.rstrip('/')}/api/ps") as response:
                if response.status != 200:
                    return []
                data = await response.json()
                return cast(list[Dict[str, Any]], data.get("models", []))
    except Exception as e:
        print(f"Error fetching loaded models: {e}")
        return []


async def unload_all_models_async(api_url: str = "http://localhost:11434") -> bool:
    """Unload all currently loaded models from VRAM"""
    try:
        loaded_models = await get_loaded_models_async(api_url)
        if not loaded_models:
            return True

        async with aiohttp.ClientSession() as session:
            for model in loaded_models:
                model_name = model.get("name", model.get("model", ""))
                if model_name:
                    payload = {"model": model_name, "keep_alive": 0}
                    async with session.post(
                        f"{api_url.rstrip('/')}/api/generate", json=payload
                    ) as resp:
                        pass

        for _ in range(5):
            await asyncio.sleep(1)
            remaining = await get_loaded_models_async(api_url)
            if not remaining:
                print("All models successfully unloaded.")
                return True

        print("Warning: Some models might still be loaded after timeout.")
        return False

    except Exception as e:
        print(f"Error unloading models: {e}")
        return False


def generate_audio_player_embed(
    audio_url: str, song_title: str, tags: str, lyrics: Optional[str] = None
) -> str:
    """Generate a sleek custom audio player embed with styled controls."""
    # Escape HTML special characters
    safe_title = (
        song_title.replace('"', "&quot;").replace("<", "&lt;").replace(">", "&gt;")
    )
    safe_tags = tags.replace('"', "&quot;").replace("<", "&lt;").replace(">", "&gt;")
    safe_lyrics = (
        (lyrics or "Instrumental")
        .replace('"', "&quot;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )

    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{safe_title}</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        html, body {{
            background: transparent;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            overflow: hidden;
        }}
        body {{
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 20px;
        }}
        .player-container {{
            background: rgba(20, 20, 25, 0.25);
            backdrop-filter: blur(10px);
            border: 1px solid rgba(255, 255, 255, 0.06);
            border-radius: 12px;
            padding: 24px;
            box-shadow: 0 8px 24px rgba(0, 0, 0, 0.2);
            max-width: 480px;
            width: 100%;
        }}
        .player-header {{
            text-align: center;
            margin-bottom: 20px;
        }}
        .player-title {{
            font-size: 20px;
            font-weight: 600;
            color: #f0f0f0;
            margin-bottom: 5px;
            letter-spacing: -0.2px;
        }}
        .player-subtitle {{
            font-size: 10px;
            color: #888;
            font-weight: 400;
            text-transform: uppercase;
            letter-spacing: 0.8px;
        }}
        
        /* Custom Audio Player */
        .custom-player {{
            margin: 18px 0;
        }}
        .progress-container {{
            width: 100%;
            height: 5px;
            background: rgba(255, 255, 255, 0.08);
            border-radius: 3px;
            cursor: pointer;
            margin-bottom: 14px;
            position: relative;
            overflow: hidden;
        }}
        .progress-bar {{
            height: 100%;
            background: rgba(255, 255, 255, 0.3);
            border-radius: 3px;
            width: 0%;
            transition: width 0.1s linear;
        }}
        .controls {{
            display: flex;
            align-items: center;
            gap: 14px;
        }}
        .play-btn {{
            width: 44px;
            height: 44px;
            min-width: 44px;
            border-radius: 50%;
            background: rgba(255, 255, 255, 0.12);
            border: 1px solid rgba(255, 255, 255, 0.15);
            color: #fff;
            font-size: 16px;
            cursor: pointer;
            transition: all 0.2s;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 0;
        }}
        .play-btn svg {{
            width: 16px;
            height: 16px;
            fill: currentColor;
        }}
        .play-btn.playing svg {{
            width: 14px;
            height: 14px;
        }}
        .play-btn:hover {{
            background: rgba(255, 255, 255, 0.2);
            transform: scale(1.05);
        }}
        .time-display {{
            font-size: 12px;
            color: #aaa;
            font-variant-numeric: tabular-nums;
            min-width: 85px;
        }}
        .volume-container {{
            display: flex;
            align-items: center;
            gap: 8px;
            flex: 1;
        }}
        .volume-btn {{
            width: 28px;
            height: 28px;
            min-width: 28px;
            border-radius: 50%;
            background: rgba(255, 255, 255, 0.08);
            border: 1px solid rgba(255, 255, 255, 0.1);
            color: #aaa;
            cursor: pointer;
            transition: all 0.2s;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 0;
        }}
        .volume-btn svg {{
            width: 14px;
            height: 14px;
            fill: currentColor;
        }}
        .volume-btn:hover {{
            background: rgba(255, 255, 255, 0.15);
            color: #ccc;
        }}
        .volume-slider {{
            flex: 1;
            height: 4px;
            background: rgba(255, 255, 255, 0.08);
            border-radius: 2px;
            cursor: pointer;
            position: relative;
        }}
        .volume-bar {{
            height: 100%;
            background: rgba(255, 255, 255, 0.3);
            border-radius: 2px;
            width: 100%;
        }}
        
        .info-section {{
            margin-top: 18px;
            padding-top: 18px;
            border-top: 1px solid rgba(255, 255, 255, 0.08);
        }}
        .info-item {{
            margin-bottom: 14px;
        }}
        .info-item:last-child {{
            margin-bottom: 0;
        }}
        .info-label {{
            font-size: 10px;
            font-weight: 600;
            color: #999;
            text-transform: uppercase;
            letter-spacing: 0.8px;
            margin-bottom: 6px;
        }}
        .info-content {{
            font-size: 13px;
            color: #ccc;
            line-height: 1.6;
        }}
        
        /* Lyrics with scrollbar only */
        .lyrics-container {{
            max-height: 120px;
            overflow-y: auto;
            font-size: 13px;
            color: #ccc;
            line-height: 1.6;
            white-space: pre-wrap;
            word-wrap: break-word;
            padding-right: 8px;
            scrollbar-width: thin;
            scrollbar-color: rgba(255, 255, 255, 0.25) rgba(255, 255, 255, 0.05);
        }}
        .lyrics-container::-webkit-scrollbar {{
            width: 5px;
        }}
        .lyrics-container::-webkit-scrollbar-track {{
            background: rgba(255, 255, 255, 0.05);
            border-radius: 3px;
        }}
        .lyrics-container::-webkit-scrollbar-thumb {{
            background: rgba(255, 255, 255, 0.25);
            border-radius: 3px;
        }}
        .lyrics-container::-webkit-scrollbar-thumb:hover {{
            background: rgba(255, 255, 255, 0.35);
        }}
        
        .download-btn {{
            display: inline-block;
            width: 100%;
            padding: 11px 18px;
            background: rgba(255, 255, 255, 0.08);
            color: #e0e0e0;
            text-align: center;
            text-decoration: none;
            border-radius: 8px;
            font-weight: 500;
            font-size: 13px;
            transition: all 0.2s;
            margin-top: 16px;
            border: 1px solid rgba(255, 255, 255, 0.1);
        }}
        .download-btn:hover {{
            background: rgba(255, 255, 255, 0.15);
            border-color: rgba(255, 255, 255, 0.2);
        }}
        
        audio {{
            display: none;
        }}
    </style>
</head>
<body>
    <div class="player-container">
        <div class="player-header">
            <div class="player-title">{safe_title}</div>
            <div class="player-subtitle">ACE Step Generation</div>
        </div>
        
        <audio id="audioPlayer" preload="auto">
            <source src="{audio_url}" type="audio/mpeg">
            <source src="{audio_url}" type="audio/wav">
        </audio>
        
        <div class="custom-player">
            <div class="progress-container" id="progressContainer">
                <div class="progress-bar" id="progressBar"></div>
            </div>
            <div class="controls">
                <button class="play-btn" id="playBtn">
                    <svg viewBox="0 0 24 24">
                        <path d="M8 5v14l11-7z"/>
                    </svg>
                </button>
                <div class="time-display" id="timeDisplay">0:00 / 0:00</div>
                <div class="volume-container">
                    <button class="volume-btn" id="volumeBtn">
                        <svg viewBox="0 0 24 24" id="volumeIcon">
                            <path d="M3 9v6h4l5 5V4L7 9H3zm13.5 3c0-1.77-1.02-3.29-2.5-4.03v8.05c1.48-.73 2.5-2.25 2.5-4.02z"/>
                        </svg>
                    </button>
                    <div class="volume-slider" id="volumeSlider">
                        <div class="volume-bar" id="volumeBar"></div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="info-section">
            <div class="info-item">
                <div class="info-label">Style</div>
                <div class="info-content">{safe_tags}</div>
            </div>
            <div class="info-item">
                <div class="info-label">Lyrics</div>
                <div class="lyrics-container">{safe_lyrics}</div>
            </div>
        </div>
        
        <a href="{audio_url}" download class="download-btn">
            <svg viewBox="0 0 24 24" style="width:14px;height:14px;fill:currentColor;vertical-align:middle;margin-right:6px;">
                <path d="M19 9h-4V3H9v6H5l7 7 7-7zM5 18v2h14v-2H5z"/>
            </svg>
            Download Song
        </a>
    </div>
    
    <script>
        const audio = document.getElementById('audioPlayer');
        const playBtn = document.getElementById('playBtn');
        const progressBar = document.getElementById('progressBar');
        const progressContainer = document.getElementById('progressContainer');
        const timeDisplay = document.getElementById('timeDisplay');
        const volumeSlider = document.getElementById('volumeSlider');
        const volumeBar = document.getElementById('volumeBar');
        const volumeBtn = document.getElementById('volumeBtn');
        const volumeIcon = document.getElementById('volumeIcon');
        
        // SVG icons
        const playIcon = '<path d="M8 5v14l11-7z"/>';
        const pauseIcon = '<path d="M6 4h4v16H6V4zm8 0h4v16h-4V4z"/>';
        const volumeHighIcon = '<path d="M3 9v6h4l5 5V4L7 9H3zm13.5 3c0-1.77-1.02-3.29-2.5-4.03v8.05c1.48-.73 2.5-2.25 2.5-4.02z"/>';
        const volumeMuteIcon = '<path d="M16.5 12c0-1.77-1.02-3.29-2.5-4.03v2.21l2.45 2.45c.03-.2.05-.41.05-.63zm2.5 0c0 .94-.2 1.82-.54 2.64l1.51 1.51C20.63 14.91 21 13.5 21 12c0-4.28-2.99-7.86-7-8.77v2.06c2.89.86 5 3.54 5 6.71zM4.27 3L3 4.27 7.73 9H3v6h4l5 5v-6.73l4.25 4.25c-.67.52-1.42.93-2.25 1.18v2.06c1.38-.31 2.63-.95 3.69-1.81L19.73 21 21 19.73l-9-9L4.27 3zM12 4L9.91 6.09 12 8.18V4z"/>';
        const volumeLowIcon = '<path d="M7 9v6h4l5 5V4l-5 5H7z"/>';
        
        // Play/Pause
        playBtn.addEventListener('click', () => {{
            const svg = playBtn.querySelector('svg');
            if (audio.paused) {{
                audio.play();
                svg.innerHTML = pauseIcon;
                playBtn.classList.add('playing');
            }} else {{
                audio.pause();
                svg.innerHTML = playIcon;
                playBtn.classList.remove('playing');
            }}
        }});
        
        // Update progress
        audio.addEventListener('timeupdate', () => {{
            const progress = (audio.currentTime / audio.duration) * 100;
            progressBar.style.width = progress + '%';
            
            const current = formatTime(audio.currentTime);
            const duration = formatTime(audio.duration);
            timeDisplay.textContent = current + ' / ' + duration;
        }});
        
        // Seek
        progressContainer.addEventListener('click', (e) => {{
            const rect = progressContainer.getBoundingClientRect();
            const percent = (e.clientX - rect.left) / rect.width;
            audio.currentTime = percent * audio.duration;
        }});
        
        // Volume
        volumeSlider.addEventListener('click', (e) => {{
            const rect = volumeSlider.getBoundingClientRect();
            const percent = (e.clientX - rect.left) / rect.width;
            audio.volume = Math.max(0, Math.min(1, percent));
            volumeBar.style.width = (percent * 100) + '%';
            updateVolumeIcon(percent);
        }});
        
        volumeBtn.addEventListener('click', () => {{
            if (audio.volume > 0) {{
                audio.dataset.prevVolume = audio.volume;
                audio.volume = 0;
                volumeBar.style.width = '0%';
                volumeIcon.innerHTML = volumeMuteIcon;
            }} else {{
                const prevVol = audio.dataset.prevVolume || 1;
                audio.volume = prevVol;
                volumeBar.style.width = (prevVol * 100) + '%';
                updateVolumeIcon(prevVol);
            }}
        }});
        
        function updateVolumeIcon(volume) {{
            if (volume === 0) {{
                volumeIcon.innerHTML = volumeMuteIcon;
            }} else if (volume < 0.5) {{
                volumeIcon.innerHTML = volumeLowIcon;
            }} else {{
                volumeIcon.innerHTML = volumeHighIcon;
            }}
        }}
        
        function formatTime(seconds) {{
            if (isNaN(seconds)) return '0:00';
            const mins = Math.floor(seconds / 60);
            const secs = Math.floor(seconds % 60);
            return mins + ':' + (secs < 10 ? '0' : '') + secs;
        }}
    </script>
</body>
</html>"""
    return html


class Tools:
    class Valves(BaseModel):
        comfyui_api_url: str = Field(
            default="http://localhost:8188",
            description="ComfyUI HTTP API endpoint.",
        )
        comfyui_api_key: str = Field(
            default="",
            description="API key for ComfyUI authentication (Bearer token). Leave empty if not required.",
            json_schema_extra={"input": {"type": "password"}},
        )
        model_name: str = Field(
            default="ACE_STEP/ace_step_v1_3.5b.safetensors",
            description="Model name for ACE Step audio generation.",
        )
        workflow_json: str = Field(
            default="",
            description="Full ACE Step workflow JSON (string).",
        )
        tags_node: str = Field(default="14", description="Node ID for tags input.")
        lyrics_node: str = Field(default="14", description="Node ID for lyrics input.")
        seed_node: str = Field(default="52", description="Node ID for seed input.")
        model_node: str = Field(
            default="40", description="Node ID for model checkpoint input."
        )
        max_wait_time: int = Field(
            default=300, description="Max wait time for generation (seconds)."
        )
        unload_ollama_models: bool = Field(
            default=False,
            description="Unload all Ollama models before calling ComfyUI.",
        )
        ollama_url: str = Field(
            default="http://host.docker.internal:11434",
            description="Ollama API URL.",
        )
        save_local: bool = Field(
            default=True,
            description="Copy the generated song to the Open Webui Storage Backend",
        )

        show_player_embed: bool = Field(
            default=True,
            description="Show the embedded audio player. If false, only returns download link.",
        )

    def __init__(self):
        self.valves = self.Valves()

    async def generate_song(
        self,
        tags: str,
        lyrics: Optional[str] = None,
        song_title: Optional[str] = None,
        __user__: Dict[str, Any] = {},
        __request__: Optional[Request] = None,
        __event_emitter__: Optional[Callable[[Any], Awaitable[None]]] = None,
    ) -> Union[str, Tuple[HTMLResponse, str]]:
        """
                Tool used to generate music with AI local backend
                Tags (prompt)
        ​
        Mainstream Music Styles
        Use short tag combinations to generate specific music styles

        electronic
        rock
        pop
        funk
        soul
        cyberpunk
        Acid jazz
        electro
        em (electronic music)
        soft electric drums
        melodic
        ​
        Scene Types
        Combine specific usage scenarios and atmospheres to generate music that matches the corresponding mood

        background music for parties
        radio broadcasts
        workout playlists
        ​
        Instrumental Elements
        saxophone
        jazz
        piano, violin
        ​
        Vocal Types
        female voice
        male voice
        clean vocals
        ​
        Professional Terms
        Use some professional terms commonly used in music to precisely control music effects

        110 bpm (beats per minute is 110)

        fast tempo

        slow tempo

        loops

        fills

        acoustic guitar

        electric bass

        ​
        Lyrics
        ​
        Lyric Structure Tags
        [outro]
        [verse]
        [chorus]
        [bridge]

        Tool Parameters:
                Required param song_title: A String, The title of the song you want to create. This will be displayed prominently in the player.
                Required param tags: A String, Mainly used to describe music styles, scenes, etc. Similar to prompts we use for other generations, they primarily describe the overall style and requirements of the audio, separated by English commas
                Required param lyrics: A string, Mainly used to describe lyrics, supporting lyric structure tags such as [verse], [chorus], and [bridge] to distinguish different parts of the lyrics. You can also input instrument names for purely instrumental music
                If you are asked to create an instrumenta piece use the parameter with "" as input, dont leave any parameter without a value
        """

        # Use a default title if none provided
        if not song_title:
            song_title = "AI Generated Song"

        if self.valves.unload_ollama_models:
            # Avoid emitting unload progress; silently perform action
            await unload_all_models_async(api_url=self.valves.ollama_url)

        if not self.valves.workflow_json:
            return "Error: Workflow JSON not provided in tool valves. Please configure."
        if not self.valves.comfyui_api_url:
            return "Error: ComfyUI API URL not configured in tool valves."

        http_api_url = self.valves.comfyui_api_url.rstrip("/")
        ws_scheme = "wss" if http_api_url.startswith("https") else "ws"
        ws_api_url = f"{ws_scheme}://{http_api_url.split('://', 1)[-1]}/ws"

        comfyui_headers = {}
        if self.valves.comfyui_api_key:
            comfyui_headers["Authorization"] = f"Bearer {self.valves.comfyui_api_key}"

        try:
            workflow_template = json.loads(self.valves.workflow_json)
            active_workflow = json.loads(json.dumps(workflow_template))

            def safe_set_input(
                wf_dict: Dict[str, Any],
                node_id: str,
                input_name: str,
                value_to_set: Any,
            ) -> bool:
                if node_id in wf_dict and "inputs" in wf_dict[node_id]:
                    wf_dict[node_id]["inputs"][input_name] = value_to_set
                    return True
                return False

            if not safe_set_input(active_workflow, self.valves.tags_node, "tags", tags):
                return f"Error: Tags node ID '{self.valves.tags_node}' not found/configured."

            if self.valves.lyrics_node:
                if not safe_set_input(
                    active_workflow, self.valves.lyrics_node, "lyrics", lyrics or ""
                ):
                    return f"Error: Lyrics node ID '{self.valves.lyrics_node}' not found/configured."

            if not safe_set_input(
                active_workflow,
                self.valves.model_node,
                "ckpt_name",
                self.valves.model_name,
            ):
                return f"Error: Model node ID '{self.valves.model_node}' not found/configured."
            active_workflow[self.valves.seed_node]["inputs"]["seed"] = random.randint(
                1, 2**32 - 1
            )
            client_id = str(uuid.uuid4())
            payload: Dict[str, Any] = {
                "prompt": active_workflow,
                "client_id": client_id,
            }

            if __event_emitter__:
                await __event_emitter__(
                    {
                        "type": "status",
                        "data": {
                            "description": "🎵 Generating song...",
                            "done": False,
                        },
                    }
                )

            async with aiohttp.ClientSession(headers=comfyui_headers) as session:
                async with session.post(
                    f"{http_api_url}/prompt",
                    json=payload,
                    timeout=aiohttp.ClientTimeout(total=30),
                ) as resp:
                    if resp.status != 200:
                        return f"ComfyUI API error on submission ({resp.status}): {await resp.text()}"
                    result = await resp.json()
                    prompt_id = result.get("prompt_id")
                    if not prompt_id:
                        return f"Error: No prompt_id from ComfyUI. Response: {json.dumps(result)}"

            # Suppress granular WS updates; only emit consolidated messages from here
            job_data = await wait_for_completion_ws(
                ws_api_url,
                http_api_url,
                prompt_id,
                client_id,
                self.valves.max_wait_time,
                None,
                headers=comfyui_headers,
            )

            current_user = Users.get_user_by_id(__user__["id"]) if __user__ else None

            audio_files = extract_audio_files(job_data)

            if audio_files:
                audio_file_info = audio_files[0]
                filename = audio_file_info["filename"]
                subfolder = audio_file_info.get("subfolder", "")

                if self.valves.save_local:
                    local_audio_url = await download_audio_to_storage(
                        __request__,
                        current_user,
                        http_api_url,
                        filename,
                        subfolder,
                        song_title or "",
                        headers=comfyui_headers,
                    )
                    if not local_audio_url:
                        return "❌ Failed to download generated audio to local cache."
                    if __event_emitter__:
                        await __event_emitter__(
                            {
                                "type": "status",
                                "data": {
                                    "description": "🎉 Song generated successfully!",
                                    "done": True,
                                },
                            }
                        )
                    if self.valves.show_player_embed:
                        # Emit the minimalistic audio player
                        html_player = generate_audio_player_embed(
                            local_audio_url, song_title, tags, lyrics
                        )
                        return (
                            HTMLResponse(
                                content=html_player,
                                headers={"Content-Disposition": "inline"},
                            ),
                            f"Song '{song_title}' generated successfully! The audio player is embedded above. Download link: {local_audio_url}",
                        )
                    else:
                        return f"🎵 Song '{song_title}' generated successfully!\n\n**Download:** [{song_title}]({local_audio_url})\n\n**Direct link:** {local_audio_url}"
                else:
                    # Fallback to ComfyUI direct link if download fails
                    subfolder_param = f"&subfolder={subfolder}" if subfolder else ""
                    comfyui_url = f"{http_api_url}/view?filename={filename}&type=output{subfolder_param}"

                    if __event_emitter__:
                        await __event_emitter__(
                            {
                                "type": "status",
                                "data": {
                                    "description": "🎉 Song generated successfully!",
                                    "done": True,
                                },
                            }
                        )
                    if self.valves.show_player_embed:
                        # Emit the minimalistic audio player with ComfyUI URL
                        html_player = generate_audio_player_embed(
                            comfyui_url, song_title, tags, lyrics
                        )
                        return (
                            HTMLResponse(
                                content=html_player,
                                headers={"Content-Disposition": "inline"},
                            ),
                            f"Song '{song_title}' generated successfully! The audio player is embedded above. Download link: {comfyui_url}",
                        )
                    else:
                        return f"🎵 Song '{song_title}' generated successfully!\n\n**Download:** [{song_title}]({comfyui_url})\n\n**Direct link:** {comfyui_url}"
            else:
                outputs_json = json.dumps(job_data.get("outputs", {}), indent=2)
                if __event_emitter__:
                    await __event_emitter__(
                        {
                            "type": "status",
                            "data": {
                                "description": "❌ Song generation finished without audio output.",
                                "done": True,
                            },
                        }
                    )
                return (
                    f"Generation completed (Job: {prompt_id}) but no audio files found. "
                    f"Job outputs: ```json\n{outputs_json}\n```"
                )

        except TimeoutError as e:
            if __event_emitter__:
                await __event_emitter__(
                    {
                        "type": "status",
                        "data": {
                            "description": f"❌ Song generation failed: {str(e)}",
                            "done": True,
                        },
                    }
                )
            return f"⏰ Generation process timed out: {str(e)}"
        except json.JSONDecodeError as e:
            if __event_emitter__:
                await __event_emitter__(
                    {
                        "type": "status",
                        "data": {
                            "description": f"❌ Song generation failed: {str(e)}",
                            "done": True,
                        },
                    }
                )
            return f"❌ Invalid workflow JSON in tool valves: {str(e)}."
        except aiohttp.ClientConnectorError as e:
            if __event_emitter__:
                await __event_emitter__(
                    {
                        "type": "status",
                        "data": {
                            "description": f"❌ Song generation failed: {str(e)}",
                            "done": True,
                        },
                    }
                )
            return f"❌ Connection Error to ComfyUI ({self.valves.comfyui_api_url} or {ws_api_url}): {str(e)}"
        except Exception as e:
            if __event_emitter__:
                await __event_emitter__(
                    {
                        "type": "status",
                        "data": {
                            "description": f"❌ Song generation failed: {str(e)}",
                            "done": True,
                        },
                    }
                )
            return f"❌ An unexpected error occurred: {str(e)}"
        # Fallback: should not reach
        return "❌ Song generation failed due to an unknown error."
